#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=60gb,walltime=10:00:00
#PBS -N wmaSeg
#PBS -V

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

if [ ! -f aparc+aseg.nii.gz ]; then
    echo "converting aparc.a2009+aseg file to nifti"
    time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt \
        docker://brainlife/freesurfer_on_mcr:6.0.2 ./convertaseg.sh
fi

echo "running segmentation"
singularity exec -e docker://brainlife/mcr:r2019a ./compiled/main

if [ ! -s classification/classification.mat ]; then
	echo "output missing"
	exit 1
fi
